### ISSUE TITLE
Sample always defaults to no Configuration Found

### ISSUE THREAD

**Issue by isaacrlevin** [stormid/Robotify.AspNetCore#1]
I did a fresh pull and I get this message in the Kestrel Window

> [Robotify] - you have no rules configured, adding default deny all just to keep you safe!

I am guessing somewhere it isn't loading the appsettings.json values, but I thought you should know

**Comment by trekco** [comment]
please see PR #2, It fixes this issue and a null reference exception

**Comment by Philo** [comment]
fixed by #2
