### ISSUE TITLE
configuration not working anymore

### ISSUE THREAD

**Issue by trekco** [stormid/Robotify.AspNetCore#12]
Looks like the configurations for groups was removed. Why is that?

this configuration does not work anymore

```
"Robotify": {
    "Enabled": true,
    "SitemapUrl": "https://musclemonkey.io/sitemap.xml",
    "CrawDelay": 10,
    "Groups": [
      {
        "UserAgent": "*",
        "Allow": ["/"]
      }
    ]
  }
```

**Comment by Philo** [comment]
Hi, robot groups was not removed, however v1.0 contains a number of refactorings that provide greater flexibility when configuring Robotify.

Please review the sample solution for how to enable robotgroups configuration from appsettings.

https://github.com/stormid/robotify-netcore/blob/1.0.0/sample/Robotify.AspNetCore.Sample/Startup.cs

**Comment by trekco** [comment]
aah, thanks, I missed that update in the readme
