### ISSUE TITLE
Exposing library and framework details

### ISSUE THREAD

**Issue by DarkCompiled** [stormid/Robotify.AspNetCore#4]
Dear Robotify team,

I noticed you announce the library used, including the version, and also details about the server framework (asp.net core), on the robots.txt content.
> \# Generated with Robotify.AspNetCore (v0.2.3.0)

You also reveal that this file is being dynamically generated.
> \# created: 2018-10-10T13:26:12

This is not acceptable to me, for security reasons.
Could you please allow to disable this behaviour, for example, on the middleware configuration?

Thank you and best regards,
Fernando

**Comment by Philo** [comment]
Hi @DarkCompiled,

I can understand your concerns here.  I have just implemented the option to disable these comments via the `appsettings.json` configuration options:

see the [appsettings.json](https://github.com/stormid/Robotify.AspNetCore/blob/master/sample/Robotify.AspNetCore.Sample/appsettings.json#L12) file within the sample application for details.

Adding `DisableFileHeaderComments` to the robotify json configuration and setting the value to `true` will bypass adding the comments to the robots.txt file.

This update can be found in version **0.3.0** and will be available on nuget shortly

**Comment by DarkCompiled** [comment]
That was fast!
Thank you very much!
