### ISSUE TITLE
Update to .NET Core 2.1

### ISSUE THREAD

**Issue by crittag** [stormid/Robotify.AspNetCore#6]
Hi @Philo 

Are you looking to update this to .NET Core 2.1?

Cheers
Greg

**Comment by Philo** [comment]
Hi @crittag,

As this is only a library, it will not target .net core 2.1 specifically.  It is currently targeting **netstandard 1.3**.  Are you having some sort compatibility issues with the library, if so could you provide some details?

The general rule for netstandard is:

> When choosing a .NET Standard version, you should consider this trade-off that the higher the version, the more APIs are available to you, while the lower the version, the more platforms implement it.

See [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target) for some additional information.

**Comment by crittag** [comment]
No compatibility issues as such. Just looking at the concept as looking to port old .NET Framework sites to .NET Core. I tend to aim for latest versions so was simply wondering if there was a reason for not being netstandard 2.0 or .NET Core 2.1 or if there were any known issues in updating.

Another thing I was also looking into was the feasibility of having the settings in appsettings.json stored in database instead. I try to keep the appsettings.json as clean as possible to allow for maximum flexibility in the web application setup.

**Comment by Philo** [comment]
> Another thing I was also looking into was the feasibility of having the settings in appsettings.json stored in database instead. I try to keep the appsettings.json as clean as possible to allow for maximum flexibility in the web application setup.

I can see how this feature could be useful, however as this would be quite a niche use-case I would want any implementation to preserve compatibility with the current setup.  I suspect this would be difficult to achieve.

If you want like this to be kept on the backlog then could you please create a new issue specifically for this feature request, I can then more easily track these requests as updates and changes are made to the library.
