### ISSUE TITLE
Allow and Disallow options in appsettings.json need to be arrays

### ISSUE THREAD

**Issue by crittag** [stormid/Robotify.AspNetCore#9]
Hi @Philo 

I have now implemented this in a project and have found that having a single path as a string in the Allow/Disallow options in appsettings.json does not parse correctly. Changing this to an array makes it function correctly.

i.e.
`"Groups": [
      {
        "UserAgent": "*",
        "Disallow": ["/"]
      },
      {
        "UserAgent": "Googlebot",
        "Disallow": ["/admin"]
      },
      {
        "UserAgent": "AnotherBot",
        "Allow": ["/search"]
      }
]`

Cheers
Greg

**Comment by Philo** [comment]
Thanks, I will look at updating the documentation to ensure there is no confusion for others
